name: KeepAlive

on:
 schedule:
 - cron: 0 0 1 * *

defaults:
 run:
  shell: bash

jobs:
 KeepAlive:
  runs-on: ubuntu-latest
  env:
   GH_TOKEN: ${{ secrets.ANTALASKAYA_TOKEN }}

  steps:

  - name: Self
    run:  gh workflow enable keepalive.yml --repo ${{ github.repository }}

  - name: WorkflowTest
    run:  gh workflow enable workflow-test.yml --repo ${{ github.repository }}
